# Generated by Django 5.0.3 on 2024-04-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(choices=[('003', '003'), ('008', '008'), ('105', '105'), ('203', '203'), ('701', '701'), ('703', '703'), ('Board Room', 'Board Room')], max_length=10),
        ),
    ]
